[KEP-1933] Proof of Concept
kubernetes/test-infra pull request #19181
Opened 2020-09-10 17:01 UTC by mlevesquedion

## Summary

This PR is a counterpart to [this PR](https://github.com/kubernetes/kubernetes/pull/94661) providing a Proof of Concept integration of the analysis proposed in [KEP-1933](https://github.com/kubernetes/enhancements/pull/1936). **It is not intended to be merged in its current state.**

The YAML is based on `config/jobs/kubernetes/sig-testing/verify.yaml`. 

I have tested the Prow job using `pj-on-kind.sh` locally and can confirm that it runs properly.

2020-09-10 17:08 UTC, mlevesquedion commented
I've signed the CLA.

2020-11-04 22:43 UTC, mlevesquedion commented
/assign @spiffxp @BenTheElder 

Aaron and Ben, I'm assigning you since you have context from https://github.com/kubernetes/kubernetes/pull/94661.

2020-11-05 19:15 UTC, spiffxp requested changes
SIG Testing is not the appropriate owner for this job.  I would suggest either SIG Instrumentation (based on the KEP), or perhaps SIG Security longer term.  Please move to one of their directories

I would also suggest following the pattern that [pull-kubernetes-typecheck uses](https://github.com/kubernetes/test-infra/blob/e711c265201915ffc732296770c0e804c89d44b7/config/jobs/kubernetes/sig-testing/typecheck.yaml), `make verify WHAT=govet-levee`

You're not skipping older release branches via `skip_branches`, if that's intentional for testing that's fine

Tests may fail because this should show up in testgrid, you should add to https://github.com/kubernetes/test-infra/blob/9c663ce1bbf49680e86afe0287accabe44023b77/config/testgrids/kubernetes/presubmits/config.yaml#L80

2020-11-05 19:16 UTC, spiffxp commented
/ok-to-test

2020-11-05 20:18 UTC, mlevesquedion commented
> SIG Testing is not the appropriate owner for this job. I would suggest either SIG Instrumentation (based on the KEP), or perhaps SIG Security longer term. Please move to one of their directories

Moved to SIG-Instrumentation for now.

> I would also suggest following the pattern that pull-kubernetes-typecheck uses, make verify WHAT=govet-levee

Thanks for the suggestion! Done.

> You're not skipping older release branches via skip_branches, if that's intentional for testing that's fine

Oops. We do want to skip those. Done.

> Tests may fail because this should show up in testgrid, you should add to ...

Done.

2020-11-05 20:36 UTC, spiffxp commented
```
could not find the referenced (TestGroup) pull-kubernetes-verify-govet-levee
```

ah right, you need an annotation to auto-generate that testgroup for you https://github.com/kubernetes/test-infra/blob/e711c265201915ffc732296770c0e804c89d44b7/config/jobs/kubernetes/sig-testing/typecheck.yaml#L15

2020-11-05 20:37 UTC, spiffxp commented on config/jobs/kubernetes/sig-instrumentation/verify-govet-levee.yaml
> +    labels:
```suggestion
    annotations:
      testgrid-create-test-group: "true"
    labels:
```

2020-11-09 17:28 UTC, chases2 commented
> ```
> could not find the referenced (TestGroup) pull-kubernetes-verify-govet-levee
> ```
> 
> ah right, you need an annotation to auto-generate that testgroup for you
> 
> https://github.com/kubernetes/test-infra/blob/e711c265201915ffc732296770c0e804c89d44b7/config/jobs/kubernetes/sig-testing/typecheck.yaml#L15

Is this a useful TestGrid row? This is a test that is only supposed to run while manually invoked, so there's no guarantee how frequently it will run or how reasonable the code it tests is.

I don't see any issues with having the test, I'm just trying to understand the use case here.

2020-11-09 17:51 UTC, mlevesquedion commented
On closer examination, I don't think we need this in testgrid.

However in @spiffxp 's original comment it sounded like not having it in testgrid could cause issues :

> Tests may fail because this should show up in testgrid

(My interpretation may be wrong.)

The intent is to be able to run the test manually on a number of PR's to confirm that everything is working properly so we can graduate to beta. We don't need testgrid for that.

2020-11-10 15:02 UTC, mlevesquedion commented
I tried removing the testgrid for the job and running `test-infra/config/tests/testgrids/config_test.go` and I got the following failure:

```
=== RUN   TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries
--- FAIL: TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries (0.01s)
    config_test.go:493: Job pull-kubernetes-verify-govet-levee does not have a matching testgrid testgroup
```

So it does look like it's preferable to have the testgrid.

Let me know if I need to make additional changes to the job.

2020-11-10 17:51 UTC, BenTheElder commented
https://testgrid.k8s.io/presubmits-kubernetes-blocking -- jobs that block PRs from merging
https://testgrid.k8s.io/presubmits-kubernetes-nonblocking -- jobs that do not block PRs from merging

Kubernetes/Kubernetes repo presubmits should be in one of these.

2020-11-10 17:56 UTC, mlevesquedion commented
Sounds good, @BenTheElder. It is in `non-blocking` right now.

2020-11-10 18:57 UTC, chases2 commented
> I tried removing the testgrid for the job and running `test-infra/config/tests/testgrids/config_test.go` and I got the following failure:
> 
> ```
> === RUN   TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries
> --- FAIL: TestKubernetesProwInstanceJobsMustHaveMatchingTestgridEntries (0.01s)
>     config_test.go:493: Job pull-kubernetes-verify-govet-levee does not have a matching testgrid testgroup
> ```
> 
> So it does look like it's preferable to have the testgrid.
> 
> Let me know if I need to make additional changes to the job.

On further reflection, you should keep the TestGrid configuration. I'm confusing what TestGrid and Configurator do, and what this repository does.

There's an [ongoing effort](https://github.com/kubernetes/test-infra/blob/6c49475cfc14f8697fb78a6075c5a529ecdd790c/config/tests/testgrids/config_test.go#L357-L359) specifically in this instance to put presubmits in TestGrid. The issue for discussion is at https://github.com/kubernetes/test-infra/issues/18159. It seems contentious, but not something to address in this PR.

You did it right the first time. Sorry about that!

2020-11-10 21:23 UTC, spiffxp approved these changes
/approve
/lgtm

2020-11-10 21:33 UTC, merged