WIP : CI Signal Policy Violation: A DashboardTab config MUST CONTAIN an alert contact email address.
kubernetes/test-infra pull request #19286
Opened 2020-09-21 10:09 UTC by RobertKielty

Some WIP on CI Signal Alert Policy enforcement 

CI Signal Policy Violation: A DashboardTab config MUST CONTAIN an alert contact email address.

2020-09-23 20:33 UTC, dims commented
/uncc

2020-10-23 08:58 UTC, RobertKielty commented
/retest

2020-10-23 13:51 UTC, RobertKielty commented
@spiffxp @BenTheElder @kubernetes/ci-signal when y'all get a chance can you review this? 

I just fixed up the PR so that it is go fmt'd properly :roll_eyes: apols for my numptyness! 

Can't remember why I marked this as WIP? 

Is this change useful/correct as-is or do we need to do more on this?

Are these tests run as part of a CI Job when a new CI job is pushed up? 
If so which job?
If not then I might need a little help with setting that up so the test are run there. 

The following run (on my feature branch) looks like ...

Test output in config_tests.txt on the below local invocation is available for review [here](https://gist.github.com/RobertKielty/84f1fc3b6a755982e5ed9eb087e53755) 

```
$ bazel test //config/tests/testgrids:go_default_test > config_tests.txt
Loading: 
Loading: 0 packages loaded
Analyzing: target //config/tests/testgrids:go_default_test (0 packages loaded, 0 targets configured)
INFO: Analyzed target //config/tests/testgrids:go_default_test (1 packages loaded, 1230 targets configured).

INFO: Found 1 test target...
[0 / 1] [Prepa] BazelWorkspaceStatusAction stable-status.txt
[1,270 / 1,271] Testing //config/tests/testgrids:go_default_test; 1s linux-sandbox
FAIL: //config/tests/testgrids:go_default_test (see /home/rkielty/.cache/bazel/_bazel_rkielty/47d03368e29206548a86533381c34b95/execroot/io_k8s_test_infra/bazel-out/k8-fastbuild/testlogs/config/tests/testgrids/go_default_test/test.log)
[1,270 / 1,271] 1 / 1 tests, 1 failed; Testing //config/tests/testgrids:go_default_test; 7s linux-sandbox
INFO: From Testing //config/tests/testgrids:go_default_test:
Target //config/tests/testgrids:go_default_test up-to-date:
  bazel-bin/config/tests/testgrids/linux_amd64_race_stripped/go_default_test
INFO: Elapsed time: 13.867s, Critical Path: 8.16s
INFO: 1 process: 1 linux-sandbox.
INFO: Build completed, 1 test FAILED, 2 total actions
INFO: Build completed, 1 test FAILED, 2 total actions
```

2020-10-23 13:54 UTC, RobertKielty commented
You can see the test in action on this PR of course :)

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/test-infra/19286/pull-test-infra-bazel/1319631568897052672

2020-11-03 19:03 UTC, spiffxp requested changes
Some suggestions

2020-11-03 19:03 UTC, spiffxp commented on config/tests/testgrids/config_test.go
> +				t.Errorf("FAIL : %s : CI Signal Policy Violation: A DashboardTab config MUST CONTAIN an alert contact email address.", dashboardtab.GetName())
Dashboard tab names are not unique.  Consider instead logging dashboard/tab (see `TestReleaseBlockingJobsMustHaveTestgridDescriptions` for an example)

2020-11-03 19:03 UTC, spiffxp commented on config/tests/testgrids/config_test.go
> +// getting subtest stats.
I'm not 100% clear on this either, don't have time to dig in.  However I feel like you could gather stats and log them if you'd like ("x / y failing policy")  I also think test-case-per-dashboard means hundreds or thousands of tests, which probably wouldn't make sense unless each test covered _all_ policies.

2021-02-17 06:46 UTC, RobertKielty commented
/remove-lifecycle stale

2021-07-17 08:05 UTC, closed without merging