Add Deployment elements to Triage Docs
kubernetes/test-infra pull request #19300
Opened 2020-09-22 00:39 UTC by MushuEE

Throw in some docs about how triage is updated/deployed.

/assign @michaelkolber

2020-09-24 16:20 UTC, spiffxp requested changes
Deployment is automated for us by prow, I would rather document that path than encourage use of the manual path.  If you feel it's necessary to have the manual info, I would put it behind a big scary warning about only being used for emergency purposes

2020-09-24 22:23 UTC, MushuEE commented on triage/README.md
> +To update Triage frontend in Production or Staging run `make push-static` or `make push-staging` respectively.
I really meant for manual, should I indicate that or not put any information in for manual updates?

2020-09-25 23:18 UTC, MushuEE commented
#19150

2020-10-12 18:00 UTC, MushuEE commented
My bad, messed up merge

2020-10-12 18:01 UTC, closed without merging