Remove required_status_checks travis for node-feature-discovery
kubernetes/test-infra pull request #19373
Opened 2020-09-27 16:11 UTC by ArangoGutierrez

required_status_checks is no longer needed can be removed as a PR ready
dependency.

*Also set squash as default merge method for both node-feature-discovery
and node-feature-discovery-operator

Signed-off-by: Carlos Eduardo Arango Gutierrez <carangog@redhat.com>

2020-09-27 16:12 UTC, ArangoGutierrez commented
/cc @marquiz 
/assign @wojtek-

2020-09-27 16:12 UTC, ArangoGutierrez commented
/assign @wojtek-t

2020-09-28 08:19 UTC, marquiz requested changes
Thanks @ArangoGutierrez 

Could you have the two separate changes as two separate PRs?

Moreover, looking at the current list of contributions/contributors, I don't think I'd like to enable squashing by default for node-feature-discovery. We can set the squash label on per PR basis when needed.

2020-09-28 13:17 UTC, ArangoGutierrez commented
> Thanks @ArangoGutierrez
> 
> Could you have the two separate changes as two separate PRs?
> 
> Moreover, looking at the current list of contributions/contributors, I don't think I'd like to enable squashing by default for node-feature-discovery. We can set the squash label on per PR basis when needed.

done, this PR will focus only on nuking what's left of TravisCI for NFD

2020-09-29 08:18 UTC, marquiz approved these changes
Thanks @ArangoGutierrez !
/lgtm

2020-09-30 13:16 UTC, ArangoGutierrez commented
/woof

2020-10-02 14:40 UTC, ArangoGutierrez commented
/woof

2020-10-05 05:09 UTC, marquiz commented
/assign @cblecker

2020-10-06 14:14 UTC, ArangoGutierrez commented
/woof

2020-10-06 14:23 UTC, nikhita commented
/assign @spiffxp 
for approval

2020-10-07 21:05 UTC, ArangoGutierrez commented
/honk

2020-10-08 20:56 UTC, ArangoGutierrez commented
/woof

2020-10-09 21:34 UTC, spiffxp approved these changes
/approve
/lgtm
/honk

2020-10-09 22:50 UTC, merged