Start to build infra around Kettle Staging
kubernetes/test-infra pull request #19399
Opened 2020-09-29 22:05 UTC by MushuEE

Here are the new pv and deployment templates for `kettle-staging` instance that will be used to test kettle changes prior to live deployment. 

My plan is to create `kettle-staging` next to kettle with it's own subset of small buckets and broken buckets to pull from. This should limit it's space utilization and still provide e2e testing options.

/area kettle
/sig testing
/cc @amwat @spiffxp

2020-10-01 00:06 UTC, amwat reviewed
/lgtm
/approve
/hold

2020-10-01 00:06 UTC, amwat commented on kettle/README.md
> +or access [log history](https://console.cloud.google.com/logs/viewer?project=k8s-gubernator&minLogLevel=0&expandAll=false&timestamp=2020-09-11T21:00:29.231000000Z&customFacets=&limitCustomFacetWidth=
nit: probably remove the fixed timestamps from this link.

2020-10-01 19:26 UTC, spiffxp requested changes
One nit, and you may need to rebase since the run.sh change is elsewhere

2020-10-01 19:26 UTC, spiffxp commented on kettle/README.md
> +This is a work in progress. `Kettle Staging` uses a similar deployment to `Kettle` however it is allowed much less dish in it's PVC and has a reduced list of buckets to pull from. It will write to th
```suggestion
This is a work in progress. `Kettle Staging` uses a similar deployment to `Kettle` with the following differences
- much less disk in its PVC
- reduced list of buckets to pull from
- writes to [build.staging](https://console.cloud.google.com/bigquery?project=k8s-gubernator&page=table&t=all&d=build&p=k8s-gubernator&redirect_from_classic=true) table only.
```

2020-10-01 19:27 UTC, spiffxp commented on kettle/README.md
> +This is a work in progress. `Kettle Staging` uses a similar deployment to `Kettle` however it is allowed much less dish in it's PVC and has a reduced list of buckets to pull from. It will write to th
(my markdown formatting might be off, it'd be worth previewing this)

2020-10-01 23:12 UTC, MushuEE commented
/label tide/merge-method-squash

2020-10-02 00:23 UTC, MushuEE commented
@spiffxp rebased

2020-10-05 18:14 UTC, spiffxp approved these changes
/approve
/lgtm

2020-10-05 18:57 UTC, spiffxp commented
(remove /hold when you see fit)

2020-10-12 17:53 UTC, MushuEE commented
/hold cancel

2020-10-12 18:04 UTC, merged