update securityContext to postgres
kubernetes/test-infra pull request #19432
Opened 2020-10-02 03:26 UTC by bernokl

2020-10-02 16:11 UTC, oomichi commented
@bernokl Could you provide the reason why we need to update it in this PR message?

/cc @oomichi

2020-10-04 19:18 UTC, bernokl commented
@oomichi the current version of the job (https://testgrid.k8s.io/sig-arch-conformance#apisnoop-conformance-gate) fails with "root execution of the PostgreSQL server is not permitted." This pr addresses the issue by making sure the job runs as the postgres user

2020-10-05 15:08 UTC, spiffxp requested changes
What testing have you done for this?

2020-10-05 15:19 UTC, spiffxp commented
/ok-to-test

2020-10-06 19:45 UTC, bernokl commented on config/jobs/kubernetes/sig-arch/conformance-gate.yaml
> +      fsGroup: 70
When We first promoted the job it failed with "root execution of the PostgreSQL server is not permitted." The intent of this pr is to run the container as the postgres user

I tested this configuration on prow.cncf.io the job is called cg-b3
https://prow.cncf.io/log?job=cg-b3&id=1313505542445993984

The postgres:12.0 container used as base for the apisnoopdb is run as root. The intent with the changing security_context is to run that container as the postgres user. The runtime should be restricted, no form of privilege is needed to run the job

2020-10-06 19:46 UTC, bernokl commented on config/jobs/kubernetes/sig-arch/conformance-gate.yaml
> +        allowPrivilegeEscalation: false
The same logic goes for changing runAsUser and runAsGroup the intent is to allow all processes involved in snoopDB to be owned by the postgres. . The runtime should be restricted, no form of privilege is needed to run the job

2020-10-12 17:26 UTC, spiffxp commented on config/jobs/kubernetes/sig-arch/conformance-gate.yaml
> +      fsGroup: 70
sorry I meant a comment in the job definition itself, so future maintainers have at least a little context without having to dig up this PR

2020-10-13 20:59 UTC, bernokl commented
/test pull-test-infra-bazel

2020-10-13 21:15 UTC, bernokl commented
/retest

2020-10-13 21:32 UTC, bernokl commented
@spiffxp I added a comment in the yaml, I hope it helps simplify understanding of the intent of the securityContext change for future maintainers.
/cc @hh

2020-10-13 21:34 UTC, spiffxp approved these changes
/approve
/lgtm

2020-10-13 21:47 UTC, merged