add mdtoc presubmit jobs
kubernetes/test-infra pull request #19565
Opened 2020-10-14 11:19 UTC by cpanato

Adding the presubmit job for the repo https://github.com/kubernetes-sigs/mdtoc

Set the owners as the owners in the repo, please let me know if need to update that.

GitHub Issue: https://github.com/kubernetes-sigs/mdtoc/issues/3

ref: 

/cc @saschagrunert @justaugustus @tallclair

2020-10-14 11:38 UTC, saschagrunert commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- tpepper
nit: let's add a newline at the end of the file

2020-10-14 11:38 UTC, saschagrunert commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- justaugustus
```suggestion
- justaugustus
```

2020-10-14 11:38 UTC, saschagrunert commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- justaugustus
```suggestion
- justaugustus
```

2020-10-14 11:40 UTC, cpanato commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- justaugustus
when I pushed I saw that :)

2020-10-14 11:44 UTC, saschagrunert approved these changes
/lgtm

2020-10-17 05:02 UTC, justaugustus commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- tpepper
```suggestion
- release-engineering-approvers
- enhancements-approvers
- tallclair
```

2020-10-17 05:03 UTC, justaugustus commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- tpepper
```suggestion
- release-engineering-reviewers
- enhancements-reviewers
- tallclair
```

2020-10-17 05:05 UTC, justaugustus requested changes
Just two nits on using aliases instead.

2020-10-17 12:22 UTC, cpanato commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- tpepper
done

2020-10-17 12:22 UTC, cpanato commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +- tpepper
Done, thanks! @justaugustus PTAL

2020-10-17 15:11 UTC, justaugustus requested changes

2020-10-17 15:11 UTC, justaugustus commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +reviewers:
```suggestion
approvers:
```

2020-10-17 15:11 UTC, justaugustus commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +approvers:
```suggestion
reviewers:
```

2020-10-17 15:44 UTC, cpanato commented on config/jobs/kubernetes-sigs/mdtoc/OWNERS
> +reviewers:
oh boy, was missing coffee

2020-10-17 16:15 UTC, justaugustus commented
/lgtm
/approve

2020-10-17 16:31 UTC, cpanato commented
@dims can you take a look when you have some time? thanks!

2020-10-17 19:20 UTC, justaugustus commented
/assign @dims @spiffxp

2020-10-17 21:18 UTC, dims commented
/approve
/lgtm

2020-10-17 21:28 UTC, merged

2020-10-29 02:12 UTC, justaugustus commented
/sig release
/area release-eng