releng: promote ci-kubernetes-build-fast-canary to be the official job
kubernetes/test-infra pull request #19660
Opened 2020-10-22 11:40 UTC by cpanato

- remove the canary job, the test shows the job is stable running in the new cluster.
- set the `ci-kubernetes-build-fast` job to use the new cluster

fixes: https://github.com/kubernetes/test-infra/issues/19484

/cc @spiffxp @justaugustus

2020-10-23 04:42 UTC, justaugustus requested changes
Needs

```yaml
      - --release=k8s-release-dev
```

after `--fast` and the testgrid alerts should include release-managers@kubernetes.io for all build jobs.

2020-10-23 07:02 UTC, cpanato commented
@justaugustus one question, when do I know we need to use the `k8s-release-dev` bucket ?
will update the PR based on your feedback, thanks!

2020-10-23 09:47 UTC, cpanato commented
updated :)

2020-10-29 15:16 UTC, justaugustus commented
/lgtm
/approve

2020-10-29 15:27 UTC, merged

2020-11-04 10:56 UTC, mborsz commented
Could you comment on the context of using k8s-release-dev? It seems to break some tests including scalability tests (see https://github.com/kubernetes/test-infra/issues/19838).

Should we revert this change (k8s-release-dev part) or are you planning to migrate existing jobs to k8s-release-dev bucket?