Remove out of date regex
kubernetes/test-infra pull request #19796
Opened 2020-11-02 13:04 UTC by hi-rustin

2020-11-02 14:27 UTC, hi-rustin commented
/cc @fejta

2020-11-02 14:41 UTC, hi-rustin commented
Hi @fejta  @alvaroaleman, I think I will continue to contribute to test-infra for a long time.  Could you become my sponsors?

2020-11-02 21:14 UTC, fejta requested changes
/ok-to-test

Will you also fix this in the approve plugin? https://github.com/kubernetes/test-infra/blob/6cc991bea964f51ee828aa3f300d404a4715a0c4/prow/plugins/approve/approve.go#L46?

2020-11-02 21:14 UTC, fejta commented on prow/plugins/lgtm/lgtm.go
> -				// lgtm.TrustedAuthorTeams is supposed to be a very short list.
Why are we dropping this comment?

2020-11-02 21:19 UTC, fejta commented
Awesome, thanks so much for the fix here!

And nice to meet you :) Yes, please keep contributing for a bit and I'll happily sponsor.

2020-11-03 01:01 UTC, hi-rustin commented on prow/plugins/lgtm/lgtm.go
> -				// lgtm.TrustedAuthorTeams is supposed to be a very short list.
TrustedAuthorTeams outdated.

2020-11-03 01:09 UTC, hi-rustin commented
> Will you also fix this in the approve plugin?

I think `no-issue` working on `approve`, because we have a `IssueRequired` configuration. So we cannot remove it.

2020-11-03 01:11 UTC, hi-rustin commented on prow/plugins/lgtm/lgtm.go
> -				// lgtm.TrustedAuthorTeams is supposed to be a very short list.
Now we only have `StickyLgtmTeam`.

2020-11-03 22:59 UTC, fejta commented
The issue is you can configure `/lgtm no-issue` to do the same thing as `/approve no-issue` so if we recognize the approve we should also lgtm?  https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approve.go#L365

2020-11-04 01:29 UTC, hi-rustin commented
> The issue is you can configure `/lgtm no-issue` to do the same thing as `/approve no-issue` so if we recognize the approve we should also lgtm? https://github.com/kubernetes/test-infra/blob/master/prow/plugins/approve/approve.go#L365

Yes, you are right. Thanks for your review.

2020-11-04 20:54 UTC, fejta approved these changes

2020-11-04 20:56 UTC, fejta commented
I started a discussion on the #prow slack channel about removing support for `/lgtm` == `/approve`, if we think this is a good idea would you want to work on that?

2020-11-04 21:10 UTC, merged

2020-11-05 01:10 UTC, hi-rustin commented
> I started a discussion on the #prow slack channel about removing support for `/lgtm` == `/approve`, if we think this is a good idea would you want to work on that?

Of course 😄

2020-11-19 06:05 UTC, hi-rustin commented
> Awesome, thanks so much for the fix here!
> 
> And nice to meet you :) Yes, please keep contributing for a bit and I'll happily sponsor.

@fejta  @alvaroaleman How about now? 😄  
I have created 15 PRs for test-infra, and 12 PRs have been merged.