vulndash: adding cpu/mem requests
kubernetes/test-infra pull request #19791
Opened 2020-10-31 17:43 UTC by cpanato

defining cpu/mem requests for the job, because this execution timeout: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-release-vulndash-update/1322405073002696704

and running locally in my machine took around 1:30 minute (2,3 GHz Quad-Core Intel Core i7 / 32 GB )

/assing @justaugustus

2020-10-31 17:45 UTC, hasheddan reviewed
/assign @justaugustus 

Probably good to set some limits on this as well 👍

2020-11-01 10:32 UTC, justaugustus requested changes
Agreed with @hasheddan; @cpanato -- would you mind setting identical `limits` here as well?

2020-11-01 14:14 UTC, cpanato commented
yes! makes totally sense, thanks for the review @hasheddan @justaugustus 
did the change, PTAL

2020-11-01 22:20 UTC, justaugustus commented
/lgtm
/approve

2020-11-01 22:20 UTC, merged