Fix ci-kubernetes-build-canary error build.
kubernetes/test-infra pull request #19804
Opened 2020-11-02 18:07 UTC by ameukam

Move the job to `k8s-infra-prow-build-trusted` cluster.

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2020-11-02 18:20 UTC, hasheddan reviewed
@ameukam apologies if I missed a conversation on this (I've been out of office for a few days), but do you have a linked issue or additional context on moving this to trusted cluster?

2020-11-02 18:46 UTC, ameukam commented
@hasheddan trying to fix https://github.com/kubernetes/kubernetes/issues/95936. 
Not sure if it's the right approach.

2020-11-04 15:57 UTC, justaugustus requested changes
/hold

I think it's entirely fine/expected for the k8s-infra-prow-build to have access to write images to the K8s Infra staging project (`k8s-staging-ci-images`).

I left a review on the other PR you opened on this --> https://github.com/kubernetes/k8s.io/pull/1393#discussion_r517017125

2020-11-06 22:01 UTC, ameukam commented
Fix applied : https://github.com/kubernetes/k8s.io/pull/1401.
/close

2020-11-06 22:01 UTC, closed without merging