Move sig-aws-* dashboards to provider-aws-*
kubernetes/test-infra pull request #19936
Opened 2020-11-13 07:48 UTC by nckturner

sig-aws is deprecated and is now a subproject under sig-cloud-provider, this naming change will reflect that.

2020-11-13 07:48 UTC, nckturner commented
There is also a reference in `./jobs/validOwners.json`, but I'm not sure how that's used.

2020-11-13 08:00 UTC, nckturner commented
/assign @gyuho @justinsb @wongma7

2020-12-09 21:00 UTC, wongma7 commented
/lgtm

2020-12-11 16:52 UTC, M00nF1sh commented
/lgtm
/approve

2020-12-14 04:03 UTC, nckturner commented
/cc @andrewsykim

2021-01-19 20:50 UTC, spiffxp commented
/test pull-test-infra-integration
#20498 (comment)

2021-01-19 20:51 UTC, spiffxp approved these changes
/approve
/lgtm

2021-01-23 17:45 UTC, spiffxp commented
/approve cancel
pull-test-infra-bazel is consistently failing
```
ERROR: /home/prow/go/src/github.com/kubernetes/test-infra/config/tests/testgrids/BUILD.bazel:25:1: Executing genrule //config/tests/testgrids:testgrid_config failed (Exit 1)
7929
2021/01/23 16:29:45 FAIL: could not apply prowjob annotations: couldn't find dashboard "sig-aws-cloud-provider-aws" for job "e2e-kops-grid-scenario-aws-cloud-controller-manager"
```

2021-01-23 17:46 UTC, spiffxp requested changes
please pass tests

2021-01-29 19:14 UTC, nckturner commented
Sorry about that, checking

2021-01-29 19:19 UTC, nckturner commented
Let's see if this works.

2021-01-30 22:11 UTC, nckturner commented
Looks like they're fixed @spiffxp

2021-02-01 17:29 UTC, spiffxp approved these changes
/approve
/lgtm

2021-02-01 18:33 UTC, nckturner commented
Rebased

2021-02-01 18:41 UTC, wongma7 commented
/lgtm

2021-02-01 18:51 UTC, merged

2021-02-01 20:11 UTC, fejta commented
Looks like we missed updating references to these renamed files:

https://github.com/kubernetes/test-infra/blob/7eb59e37d822397fc7d30ad9e3d1574342d189fa/config/prow/autobump-config.yaml#L17-L18

2021-02-01 20:12 UTC, fejta commented
Hmm, not convinced this PR renamed those files, NM

2021-02-02 01:30 UTC, nckturner commented
Which references to those files are you referring to?

On Mon, Feb 1, 2021 at 12:11 PM Erick Fejta <notifications@github.com>
wrote:

> Looks like we missed updating references to these renamed files:
>
>
> https://github.com/kubernetes/test-infra/blob/7eb59e37d822397fc7d30ad9e3d1574342d189fa/config/prow/autobump-config.yaml#L17-L18
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kubernetes/test-infra/pull/19936#issuecomment-771126103>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJGJELK7QVM5JA2QHQFSDDS44DHVANCNFSM4TUIGY7Q>
> .
>