Add a k8s conformance job to testgrid with containerd runtime on ppc64le
kubernetes/test-infra pull request #20180
Opened 2020-12-09 12:37 UTC by Rajalakshmi-Girish

To test-grid, add the job that runs conformance tests against latest version of kubernetes with containerd as runtime on local ppc64le cluster.

Bucket details to the log path:
 ppc64le-kubernetes/logs/periodic-kubernetes-containerd-conformance-test-ppc64le

2020-12-09 12:38 UTC, Rajalakshmi-Girish commented
/cc @mkumatag

2020-12-09 13:24 UTC, mkumatag requested changes
nit: rewording

2020-12-09 13:24 UTC, mkumatag commented on config/testgrids/conformance/conformance-all.yaml
> +- name: ppc64le-containerd-conformance
for better reading can you postfix `containerd` instead of infix

2020-12-09 13:24 UTC, mkumatag commented
/ok-to-test

2020-12-10 05:20 UTC, mkumatag commented
/lgtm

2020-12-11 03:58 UTC, michelle192837 approved these changes

2020-12-11 04:08 UTC, dims commented
/approve
/lgtm

2020-12-11 04:09 UTC, merged