Add rerun_auth_config for post-kubernetes-push-e2e-*-test-images
kubernetes/test-infra pull request #20454
Opened 2021-01-12 20:21 UTC by chewong

Signed-off-by: Ernest Wong <chuwon@microsoft.com>

adding @aojea, @claudiubelu, and myself to `rerun_auth_configs` of all `post-kubernetes-push-e2e-*-test-images` jobs.

2021-01-12 20:33 UTC, aojea commented
/assign @spiffxp

2021-01-12 21:50 UTC, spiffxp requested changes

2021-01-12 21:50 UTC, spiffxp commented on config/jobs/image-pushing/k8s-staging-e2e-test-images.sh
> +          - claudiubelu
Please also give rerun access to @kubernetes/test-infra-admins and @kubernetes/release-managers
```suggestion
      rerun_auth_configs:
        github_team_slugs:
          - org: kubernetes
            slug: release-managers
          - org: kubernetes
            slug: test-infra-admins            
        github_users:
          - aojea
          - chewong
          - claudiubelu
```

2021-01-13 00:54 UTC, cjwagner requested changes

2021-01-13 00:54 UTC, cjwagner commented on config/jobs/image-pushing/k8s-staging-e2e-test-images.sh
> +      rerun_auth_configs:
This should be singular. See this GoDoc: https://godoc.org/k8s.io/test-infra/prow/config#JobBase

2021-01-13 09:08 UTC, aojea commented
/cc

2021-01-13 19:51 UTC, cjwagner requested changes

2021-01-13 19:51 UTC, cjwagner commented on config/jobs/image-pushing/k8s-staging-e2e-test-images.yaml
> +      rerun_auth_configs:
Looks like this needs to be regenerated. Still plural.

2021-01-13 20:03 UTC, cjwagner approved these changes

2021-01-13 20:13 UTC, merged