Standardizes lgtm/approve workflows for sig-release
kubernetes/test-infra pull request #20934
Opened 2021-02-21 21:32 UTC by supriya-premkumar

Changes:

- Adds the following repos to lgtm and approve plugins.
   - kubernetes-sigs/downloadkubernetes
   - kubernetes-sigs/k8s-container-image-promoter
   - kubernetes-sigs/mdtoc
   - kubernetes-sigs/release-notes
   - kubernetes-sigs/zeitgeist
   - kubernetes/publishing-bot
   - kubernetes/release
   - kubernetes/sig-release
- Fixes kubernetes/sig-release#1464

2021-02-21 21:52 UTC, dims commented
/ok-to-test

2021-02-21 22:57 UTC, dims commented
/assign @justaugustus @saschagrunert

2021-02-21 22:57 UTC, dims commented
nice work @supriya-premkumar .. thanks!

/lgtm

2021-02-21 23:22 UTC, justaugustus requested changes
Thanks so much for working on this, @supriya-premkumar!
I've got one microscopic nit (that the list of repos should be alpha-sorted) and I've left fixes as code suggestions. :)

2021-02-21 23:22 UTC, justaugustus commented on config/prow/plugins.yaml
> +  - kubernetes-sigs/k8s-container-image-promoter
```suggestion
  - kubernetes-sigs/k8s-container-image-promoter
  - kubernetes-sigs/k8s-gsm-tools
```

2021-02-21 23:22 UTC, justaugustus commented on config/prow/plugins.yaml
> +  - kubernetes/sig-release
```suggestion
  - kubernetes/sig-release
  - kubernetes/test-infra
```

2021-02-21 23:32 UTC, supriya-premkumar commented on config/prow/plugins.yaml
> +  - kubernetes-sigs/k8s-container-image-promoter
Ack.

2021-02-21 23:32 UTC, supriya-premkumar commented on config/prow/plugins.yaml
> +  - kubernetes/sig-release
Ack

2021-02-21 23:59 UTC, justaugustus commented
Thanks again!
/lgtm
/approve

Over to @dims for the `/approve` on `config/`!

2021-02-22 00:32 UTC, dims commented
/approve
/hold

@justaugustus feel free to remove hold when appropriate (need to notify folks via email?)

2021-03-01 19:56 UTC, dims commented
/hold cancel

it's been a week!

2021-03-01 23:09 UTC, justaugustus commented
@dims -- Apologies for not dropping the hold! This was discussed and approved on [last week's SIG Release meeting](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#heading=h.ukbaidczvy3r).

@supriya-premkumar -- Thanks again for this awesome contribution!

cc: @kubernetes/sig-release-leads 
/test pull-test-infra-integration

2021-03-01 23:30 UTC, merged

2021-03-01 23:45 UTC, supriya-premkumar commented
> @dims -- Apologies for not dropping the hold! This was discussed and approved on [last week's SIG Release meeting](https://docs.google.com/document/d/1Fu6HxXQu8wl6TwloGUEOXVzZ1rwZ72IAhglnaAMCPqA/edit#heading=h.ukbaidczvy3r).
> 
> @supriya-premkumar -- Thanks again for this awesome contribution!
> 
> cc: @kubernetes/sig-release-leads
> /test pull-test-infra-integration

Thank you @dims  and @justaugustus. This is my first contribution to K8s repo that got merged. It feels surreal ❤️