prow.k8s.io bumping PR automatically merged
kubernetes/test-infra pull request #21314
Opened 2021-03-11 15:11 UTC by chaodaiG

This PR enables PR created by k8s-ci-robot with trusted label to be automatically merged. Since k8s-ci-robot automatically creates autobump PRs, there is no more manual step needed any more for bumping prow.k8s.io.

Part of: https://github.com/kubernetes/enhancements/tree/master/keps/sig-testing/2539-continuously-deploy-k8s-prow

/hold
Will not merge this until:
- Announced widely in k8s-dev community
- KEP was moved to implementable phase

2021-03-11 15:11 UTC, chaodaiG commented
/cc @justaugustus @cjwagner

2021-03-12 04:02 UTC, cjwagner approved these changes
/hold

2021-03-12 16:03 UTC, spiffxp requested changes
Whatever label you decide to use, it should be added to https://github.com/kubernetes/test-infra/blob/master/label_sync/labels.yaml

My preference would be to restrict to the repo it's used for, and (not a strong opinion) make it either:
- yellow (jumps out as visually distinct, humans didn't look at this, not red since it is not blocking merge)
- green (relates to lgtm/approve)
- match whatever color other labels of this prefix use

2021-03-12 21:59 UTC, chaodaiG commented on config/prow/config.yaml
> +    - auto/trusted-pullrequest
The bot has already signed CLA I believe. And the label is added in a separate PR #21313 , which has been updated to use `skip-review` label instead. Will update this PR once the other one is merged

2021-03-22 20:24 UTC, spiffxp commented on config/prow/config.yaml
> +    - auto/trusted-pullrequest
I might be wrong, but I thought gating merges on the presence of the `cncf-cla: yes` label is how we enforced that all code contributed to this project has come through the CLA.

2021-04-01 16:23 UTC, spiffxp commented
Confirmed kubernetes-dev@ has been notified https://groups.google.com/g/kubernetes-dev/c/nke9PYaGTnY/m/nrQ6hVDfCgAJ

2021-04-01 16:24 UTC, spiffxp approved these changes
/approve
/lgtm
/hold
remove /hold when ready to deploy

2021-04-01 16:25 UTC, chaodaiG commented
/unhold
Let's rock

2021-04-01 16:37 UTC, merged