wg-k8s-infra: Add presubmit to validate k8s resources
kubernetes/test-infra pull request #21663
Opened 2021-04-05 19:09 UTC by ameukam

Ref: https://github.com/kubernetes/k8s.io/issues/1734

/wg k8s-infra

Signed-off-by: Arnaud Meukam <ameukam@gmail.com>

2021-04-05 19:35 UTC, ameukam commented
/assign @spiffxp

2021-04-06 20:36 UTC, spiffxp requested changes

2021-04-06 20:36 UTC, spiffxp commented on config/jobs/kubernetes/wg-k8s-infra/k8sio-presubmit.yaml
> +        - -p policies/ */*.yaml
Is this one level deep or recursive descent?

2021-04-06 20:36 UTC, spiffxp commented on config/jobs/kubernetes/wg-k8s-infra/k8sio-presubmit.yaml
> +    run_if_changed: '\.yaml$'
Can we isolate this to paths with k8s yaml? There is some yaml that is not k8s

2021-08-04 22:10 UTC, ameukam commented
Need to update this with the recent changes in https://git.k8s.io/k8s.io

/remove-lifecycle rotten

2022-04-03 23:24 UTC, closed without merging