Kubernetes v1.22 Code Freeze
kubernetes/test-infra pull request #22775
Opened 2021-07-02 16:49 UTC by thejoycekung

This PR enables code freeze for `kubernetes/kubernetes` on the master branch.

/hold
This PR should only be merged after Thursday, July 8, 2021 18:00 PDT.

/sig release
/area release-eng

cc: @kubernetes/release-team-leads @kubernetes/release-engineering

2021-07-02 17:17 UTC, puerco requested changes
Thanks @thejoycekung , just one nit, we also need to add the 1.22 branch to avoid making a second PR when we create the branch :point_down:

2021-07-02 17:17 UTC, puerco commented on config/prow/config.yaml
> +    - master
```suggestion
    - master
    - release-1.22
```
I just noticed a little error here, we have to add the 1.22 branch (`release-1.22`) to this exclusion and also to the requirements below. The branch does not exist yet, but we want code freeze to also apply to it when we create it in `v1.22.0-rc.0`.

2021-07-02 17:17 UTC, puerco commented on config/prow/config.yaml
> +    - master
Same thing here:
```suggestion
    - master
    - release-1.22
```

2021-07-08 14:04 UTC, ameukam commented
/lgtm

2021-07-08 14:05 UTC, cpanato approved these changes
/lgtm

2021-07-08 14:07 UTC, xmudrii approved these changes

2021-07-09 00:06 UTC, puerco commented
/assign @dims @cblecker @spiffxp

2021-07-09 00:20 UTC, puerco commented
/priority critical-urgent

2021-07-09 00:50 UTC, dims commented
/approve
/hold until needed.

2021-07-09 01:32 UTC, puerco commented
/hold cancel

2021-07-09 01:46 UTC, merged

2021-07-09 01:51 UTC, puerco commented
:snowflake:  **Code Freeze is now in effect.**
/cc @kubernetes/release-team 
Thank you @thejoycekung!