Add: create image pushing job for kube-scheduler-simulator
kubernetes/test-infra pull request #23567
Opened 2021-09-12 00:36 UTC by sanposhiho

2021-09-13 16:23 UTC, spiffxp approved these changes
/approve
/lgtm

2021-09-13 16:23 UTC, spiffxp commented
/hold

2021-09-13 16:24 UTC, spiffxp requested changes

2021-09-13 16:24 UTC, spiffxp commented on config/jobs/image-pushing/k8s-staging-sched-simulator.yaml
> +              - --scratch-bucket=gs://k8s-staging-sched-simulator
```suggestion
              - --scratch-bucket=gs://k8s-staging-sched-simulator-gcb
```

2021-09-14 12:01 UTC, sanposhiho commented on config/jobs/image-pushing/k8s-staging-sched-simulator.yaml
> +              - --scratch-bucket=gs://k8s-staging-sched-simulator
Thanks :)

2021-09-14 12:01 UTC, sanposhiho commented
@spiffxp thanks for reviewing, fixed it

2021-09-14 13:11 UTC, spiffxp approved these changes
/approve
/lgtm

2021-09-14 14:27 UTC, sanposhiho commented
changed to use k8s-staging-test-infra/image-builder instead of k8s-testimages/image-builder.
Ref: https://github.com/kubernetes/test-infra/pull/23587

2021-09-14 14:35 UTC, spiffxp commented on config/jobs/image-pushing/k8s-staging-sched-simulator.yaml
> +          - image: gcr.io/k8s-testimages/image-builder:v20210622-762366a
```suggestion
          - image: gcr.io/k8s-staging-test-infra/image-builder:v20210913-fc7c4e84f6
```

2021-09-14 14:36 UTC, spiffxp commented
Can you rebase to drop the merge commit

2021-09-14 14:38 UTC, sanposhiho commented
> Can you rebase to drop the merge commit

👍  done

2021-09-14 14:48 UTC, spiffxp approved these changes
/approve
/lgtm

2021-09-14 14:49 UTC, merged