node: Move dockershim tests to their own job
kubernetes/test-infra pull request #24326
Opened 2021-11-11 16:36 UTC by endocrimes

This commit excludes Dockershim tests from the Serial job and moves them
to their own job. This is ahead of dockershim support being removed from
the kubelet to help clean up test flakiness.

/sig node
/cc @SergeyKanzhelev @dims

2021-11-11 16:37 UTC, ehashman requested changes
Can we please also update the periodics to split?

2021-11-11 16:52 UTC, endocrimes commented
/retest

2021-11-11 18:04 UTC, endocrimes commented
@ehashman updated

2021-11-11 18:40 UTC, dims commented
/approve

will leave lgtm for @SergeyKanzhelev or @ehashman

2021-11-12 05:25 UTC, SergeyKanzhelev approved these changes
thank you!

2021-11-12 05:36 UTC, merged