OWNERS: Update aliases with latest release managers
kubernetes/test-infra pull request #24809
Opened 2022-01-07 07:07 UTC by palnabarun

- Add palnabarun to release-engineering-approvers,
  release-engineering-reviewers, publishing-bot-reviewers
- Add Verolop to release-engineering-approvers,
  release-engineering-reviewers
- Add xmudrii to release-engineering-approvers

Signed-off-by: Nabarun Pal <pal.nabarun95@gmail.com>

2022-01-09 12:05 UTC, justaugustus requested changes
@palnabarun -- tiny nit on the alpha-sorting :)

2022-01-09 12:05 UTC, justaugustus commented on OWNERS_ALIASES
> +    - Verolop # Release Manager
```suggestion
    - Verolop # Release Manager
    - xmudrii # Release Manager
```

2022-01-09 12:05 UTC, justaugustus commented on OWNERS_ALIASES
> +    - Verolop # Release Manager
```suggestion
    - Verolop # Release Manager
    - xmudrii # Release Manager
```

2022-01-17 11:24 UTC, palnabarun commented on OWNERS_ALIASES
> +    - Verolop # Release Manager
Done!

2022-01-17 11:24 UTC, palnabarun commented on OWNERS_ALIASES
> +    - Verolop # Release Manager
Done!

2022-01-18 12:44 UTC, justaugustus approved these changes
/assign @spiffxp @BenTheElder @stevekuznetsov

2022-01-21 15:48 UTC, justaugustus commented
@kubernetes/sig-testing-leads -- Poke for review!

2022-02-09 04:37 UTC, justaugustus commented
@kubernetes/sig-testing -- Bump for approval!

2022-02-09 18:23 UTC, cjwagner approved these changes

2022-02-09 18:34 UTC, merged