Add descheduler 1.23 tests
kubernetes/test-infra pull request #25093
Opened 2022-02-02 18:59 UTC by damemi

This updates the descheduler repo for 1.23 presubmit testing. Previous update: https://github.com/kubernetes/test-infra/pull/23308

2022-02-02 19:00 UTC, damemi reviewed
/cc @ingvagabund @seanmalloy

2022-02-03 05:01 UTC, seanmalloy requested changes

2022-02-03 05:01 UTC, seanmalloy commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-release-1.23.yaml
> +    - ^release-1.22$
Shouldn't it be like this ...
```suggestion
    - ^release-1.23$
```

2022-02-03 05:01 UTC, seanmalloy commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-release-1.23.yaml
> +    - release-1.22
Same here ...
```suggestion
    - release-1.23
```

2022-02-03 18:57 UTC, damemi commented
@seanmalloy thanks, good catches.. updated

2022-02-03 19:44 UTC, seanmalloy commented
/lgtm

2022-02-03 19:45 UTC, merged