Add labels to `ConfigMaps` created by `updateconfig`
kubernetes/test-infra pull request #26046
Opened 2022-04-20 23:10 UTC by upodroid

Part of #26045

2022-04-20 23:43 UTC, fejta commented
/ok-to-test
/assign @mpherman2 @chaodaiG 

Any concerns here? Seems fine to me...

2022-04-20 23:47 UTC, chaodaiG requested changes
lgtm, only nit: duplicated hardcoded values should better be defined once above

2022-04-21 00:05 UTC, upodroid commented
> lgtm, only nit: duplicated hardcoded values should better be defined once above

Fixed

2022-04-21 14:47 UTC, chaodaiG approved these changes

2022-04-21 15:10 UTC, merged