Switch to releng-ci:latest-go1.18-bullseye for go 1.17 jobs
kubernetes/test-infra pull request #26109
Opened 2022-04-27 07:59 UTC by saschagrunert

The latest version of the releng-ci image is the go1.18bullseye tag,
which is what we should prefer for overall consistency.

2022-04-27 08:01 UTC, saschagrunert commented
For the e2e framework approvers, PTAL @andrewsykim @BenTheElder @spiffxp @vladimirvivien

2022-04-27 12:29 UTC, cpanato approved these changes
/lgtm

2022-04-27 15:03 UTC, BenTheElder commented
Go 1.18 has breaking changes, are all these projects prepared for this? Have we spoken to approvers in the project?
(I am emeritus in e2e-framework)

2022-04-27 18:21 UTC, vladimirvivien reviewed
/lgtm

2022-04-28 03:47 UTC, justaugustus requested changes
@saschagrunert -- I would descope this to RelEng projects only

2022-04-28 06:52 UTC, saschagrunert commented
> @saschagrunert -- I would descope this to RelEng projects only

Done :+1:

2022-04-28 11:15 UTC, justaugustus approved these changes
Thanks @saschagrunert!

2022-04-28 11:20 UTC, dims commented
/approve
/lgtm

2022-04-28 11:36 UTC, merged