Remove outdated flags around GitHub tokens
kubernetes/test-infra pull request #26385
Opened 2022-05-23 10:05 UTC by JohnTitor

These flags were deprecated in #21891, now it's May 2022, and we could remove them.

2022-05-23 14:35 UTC, stevekuznetsov approved these changes

2022-05-23 21:25 UTC, fejta approved these changes

2022-05-23 21:27 UTC, fejta requested changes
This flag is still in use:

https://github.com/kubernetes/test-infra/blob/164e5078198201cefdb03855827ae15b9e673fdc/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L18

https://github.com/kubernetes/test-infra/blob/164e5078198201cefdb03855827ae15b9e673fdc/config/jobs/kubernetes/test-infra/test-infra-trusted.yaml#L570

2022-05-24 08:37 UTC, JohnTitor commented
Good point, removed some more flags/testcases using them via 274cb40cb480219d236958d31af2c00401fe45fc

2022-05-24 19:07 UTC, fejta approved these changes
thanks!

2022-05-24 19:21 UTC, merged