jira:  add custom fields qa_contact and target_version
kubernetes/test-infra pull request #26464
Opened 2022-06-01 21:29 UTC by hoxhaeris

Add `jira` and `fake_jira` methods to get the value for two Jira custom fields:

- QA Contact
- Target Version

These custom fields are part of the `Unknowns` key of the `IssueFields` type.  

The same logic used in the `GetIssueSecurityLevel` method applies here. `GetIssueSecurityLevel`  is split to include a generic `GetUnknownField` function.

2022-06-02 21:24 UTC, AlexNPavel commented
/ok-to-test

2022-06-07 20:19 UTC, AlexNPavel requested changes

2022-06-07 20:19 UTC, AlexNPavel commented on prow/jira/jira.go
> +	var obj *jira.Version
This should be a `[]*jira.Version`.

2022-06-08 10:21 UTC, hoxhaeris commented on prow/jira/jira.go
> +	var obj *jira.Version
Fixed

2022-06-09 17:28 UTC, AlexNPavel approved these changes

2022-06-09 17:43 UTC, merged