Add descheduler 1.25 tests
kubernetes/test-infra pull request #27348
Opened 2022-09-02 02:36 UTC by a7i

As part of this change, we are updating the descheduler repo for 1.25 presubmits testing. Previous update: https://github.com/kubernetes/test-infra/pull/25833

Related issue: https://github.com/kubernetes-sigs/descheduler/issues/844

2022-09-02 02:38 UTC, a7i commented
/cc @pravarag @damemi

2022-09-02 14:48 UTC, damemi reviewed
/ok-to-test
/approve

2022-09-03 14:05 UTC, a7i commented
@chase2 and @wojtek-t would you please take a look?

2022-09-03 18:58 UTC, ingvagabund requested changes

2022-09-03 18:58 UTC, ingvagabund commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml
>    - name: pull-descheduler-test-e2e-k8s-master-1-23
1-23 -> 1-24

2022-09-03 18:58 UTC, ingvagabund commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml
>    - name: pull-descheduler-test-e2e-k8s-master-1-22
1-22 -> 1-23

2022-09-03 18:58 UTC, ingvagabund commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml
>    - name: pull-descheduler-test-e2e-k8s-master-1-24
1-24 -> 1-25

2022-09-04 07:48 UTC, ingvagabund commented on config/jobs/kubernetes-sigs/descheduler/descheduler-presubmits-master.yaml
> +          value: "v1.25.0"
https://hub.docker.com/layers/kindest/node/v1.25.0/images/sha256-db0089929bbf03b5c6f2a4e2a7000e0b362900dbb5395d2c5f62a5a1daf8d54b?context=explore

2022-09-04 07:53 UTC, ingvagabund commented
/lgtm

2022-09-04 07:54 UTC, merged