add optional presubmit for alibabacloud provider with secrets-store-csi
kubernetes/test-infra pull request #28032
Opened 2022-11-16 13:53 UTC by DahuK

PR adds:
1. optional presubmit testing for alibabacloud provider with secrets-store-csi
2. external secret in order to use it in alibabacloud provider tests

2022-11-17 20:24 UTC, chases2 commented
Please get approval and review from someone in [config/jobs/kubernetes-sigs/secrets-store-csi-driver/OWNERS](https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-sigs/secrets-store-csi-driver/OWNERS) who has context. If after that you still need further approval, feel free to assign to the prow oncall (or to me)

2022-11-29 23:26 UTC, aramase commented
/cc

2023-03-30 00:57 UTC, aramase commented
/remove-lifecycle rotten

2023-05-08 12:50 UTC, DahuK commented
@aramase @hixichen @ritazh
this has held for a long time, could you please take a time for reviewing this and help to move forward, thanks!

2023-05-18 17:00 UTC, aramase requested changes

2023-05-19 03:58 UTC, DahuK commented on config/jobs/kubernetes-sigs/secrets-store-csi-driver/secrets-store-csi-driver-config.yaml
> +    run_if_changed: "^charts/.*"
> fix this, thanks!

2023-05-19 03:58 UTC, DahuK commented on config/jobs/kubernetes-sigs/secrets-store-csi-driver/secrets-store-csi-driver-config.yaml
> +        - image: gcr.io/k8s-staging-test-infra/kubekins-e2e:v20221109-489d560851-master
updated

2023-05-19 04:02 UTC, DahuK commented on config/prow/cluster/build/build_kubernetes-external-secrets_customresource.yaml
> +  backendType: alicloudSecretsManager
yes, it looks like the project using archived [kubenrtes-external-secrets](https://github.com/external-secrets/kubernetes-external-secrets#alibaba-cloud-kms-secret-manager), and I have tested the alicloudSecretsManager backend in our cluster

2024-01-19 18:29 UTC, aramase commented
/remove-lifecycle stale

2024-04-19 03:36 UTC, DahuK commented
/remove-lifecycle stale

2024-04-21 12:39 UTC, DahuK commented
@aramase  my apologies for the delayed update. Please review it and another relevant [PR](https://github.com/kubernetes-sigs/secrets-store-csi-driver/pull/1091),   and let me know if there's anything I need to add.

2024-08-06 23:45 UTC, BenTheElder commented
Relevant announcements:

https://groups.google.com/a/kubernetes.io/g/dev/c/p6PAML90ZOU/m/11sDguoxAQAJ
https://groups.google.com/a/kubernetes.io/g/dev/c/qzNYpcN5la4

We're not permitting any more external secrets like this, which in retrospect were a HUGE mistake.

If you want to run on Kubernetes's community CI, you need to provide resources to SIG K8s Infra via an agreement with the CNCF so we understand:
- how much is available
- how long are the resources committed
- visibility into usage (so we know when we're about to run out)
- access granted to the CNCF, and then SIG K8s Infra leads, and then also some community members, so we're not left with defunct resources nobody can control when employees that set them up leave

IF they meet those requirements, we can arrange to use them from the community clusters.

`cluster: default` which has these external secrets is another old company-internal resource that is being shut down.

Closing this as per https://github.com/kubernetes/test-infra/issues/33226

2024-08-06 23:45 UTC, closed without merging