Order the args for in-place resize pull job in the same order as alpha-features pull job
kubernetes/test-infra pull request #28112
Opened 2022-11-24 18:46 UTC by vinaykul

Try the same order of arguments as the alpha-features pull job to see if that's the reason in-place resize pull job failed where alpha-features pull job and cgroupv2 CI jobs work fine.

https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/102884/pull-kubernetes-e2e-inplace-pod-resize-containerd-main-v2/1592565922474758144/

2022-11-24 18:47 UTC, vinaykul commented
/assign @bobbypage @endocrimes @SergeyKanzhelev

2022-11-29 02:54 UTC, bobbypage commented
Chatted offline, based on investigation the ordering of `--repo` changed the cwd of the in bootstrap.py.

/lgtm

2022-12-02 12:20 UTC, endocrimes requested changes
I think the only thing we need to re-add is `--job` otherwise lgtm.

2022-12-02 12:20 UTC, endocrimes commented on config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml
> +        - --root=/go/src
```suggestion
        - --root=/go/src
        - "--job=$(JOB_NAME)"
```

2022-12-02 14:30 UTC, vinaykul commented on config/jobs/kubernetes/sig-node/sig-node-presubmit.yaml
> +        - --root=/go/src
Done. I just fixed it.

2022-12-02 14:43 UTC, endocrimes approved these changes
/approve
/lgtm

2022-12-02 14:45 UTC, merged