Changes kops vpc plugin to amazonvpc for presubmit scale job
kubernetes/test-infra pull request #29323
Opened 2023-04-18 00:06 UTC by ashishranjan738

This commit changes kops vpc plugin to amazonvpc for presubmit scale jobs.

2023-04-18 00:13 UTC, shyamjvs commented
/lgtm
/hold

cc @BenTheElder or @justinsb - for approval

2023-04-18 00:13 UTC, shyamjvs commented
/ok-to-test

2023-04-19 08:42 UTC, hakman requested changes
Let's add CNI as suffix. We will want to add some tests with other CNIs until things work as expected.
/cc @justinsb

2023-04-19 08:42 UTC, hakman commented on config/jobs/kubernetes/kops/build_jobs.py
>              name='presubmit-kops-aws-scale',
```suggestion
            name='presubmit-kops-aws-scale-amazonvpc',
```

2023-04-19 08:42 UTC, hakman commented on config/jobs/kubernetes/kops/build_jobs.py
>              name_override='kops-aws-scale',
```suggestion
            name_override='kops-aws-scale-amazonvpc',
```

2023-04-20 14:13 UTC, justinsb commented on config/jobs/kubernetes/kops/build_jobs.py
>              name_override='kops-aws-scale',
Should we have both jobs for a bit?

2023-04-20 14:30 UTC, justinsb commented
I'm also OK though if we want to just tweak this job, get it working, then create a few jobs to cover a few scenarios!

2023-04-26 18:57 UTC, ashishranjan738 commented
@justinsb @hakman I have updated the job names. Let me know if we are good for merge

2023-04-26 21:15 UTC, justinsb commented
Thanks @ashishranjan738 

/approve
/lgtm
/hold cancel

2023-04-26 21:26 UTC, merged