migrate external-snapshotter to community cluster
kubernetes/test-infra pull request #29763
Opened 2023-06-11 10:40 UTC by PatsyVilla

migrate `kubernetes-csi/external-snapshotter` jobs from `default` cluster to `eks-prow-build-cluster`

Ref: https://github.com/kubernetes/test-infra/issues/29722

2023-06-11 10:46 UTC, rjsadow commented
Thanks @PatsyVilla 
/ok-to-test
/hold for review from csi owners @msau42 @saad-ali @xing-yang @jsafrane @pohly

2023-06-11 20:42 UTC, pohly requested changes
All Kubernetes-CSI jobs are generated by https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/gen-jobs.sh

Please don't edit them manually. Instead, update that script and run it to update all jobs.

2023-06-12 12:24 UTC, pohly commented
I have no idea, and I also don't know how to measure them.

2023-06-12 17:54 UTC, xing-yang commented
There are resource limits specified here:
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/gen-jobs.sh#L132-L145

2023-06-12 18:02 UTC, rjsadow commented
Thanks @xing-yang, with the transition we'll need to have resource requests and limits for cpu and memory on all jobs. Currently, csi doesn't have any limits AFAIK, and the comment in that script indicates it could need to be as high as 20 cpu per job.

2023-06-14 15:56 UTC, jsafrane commented
No, `2000m` means 2 CPUs.

2023-06-14 17:05 UTC, rjsadow commented
I was referring to the comment https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/gen-jobs.sh#L137

2023-06-15 12:27 UTC, jsafrane commented
https://github.com/kubernetes/test-infra/blob/master/config/jobs/kubernetes-csi/gen-jobs.sh#L137 says "3-20m", which I read as 3 millicores - 20 millicores (i.e. almost nothing), when compared to 9Gi RAM and 2 CPUs used for compilation. 10 CPUs and 16 GB RAM in this PR seems to be a huge overkill.

2023-06-23 13:38 UTC, rjsadow commented
/close

2023-06-23 13:38 UTC, closed without merging