Manually Remove Kubernetes 1.24 jobs
kubernetes/test-infra pull request #30563
Opened 2023-08-30 02:01 UTC by jeremyrickard

This PR is intended to drop the 1.24 jobs by replicating the work done to remove the 1.23 jobs in https://github.com/kubernetes/test-infra/pull/29387. 

Notably:

* This continues the pattern of  commenting  out k8s-beta in `releng/test_config.yaml`.
* k8s beta dashboard content is commented out with TODO comments for 1.29
* Removes 1.24 jobs sig-windows

Note: there were some TODO commented out things left over from the previous attempt this that should have been undone when we created the 1.28 branch and jobs. We should double check everything when it is time to do the 1.29 jobs. 

/assign @xmudrii @jimangel @marosset 
cc https://github.com/orgs/kubernetes/teams/release-engineering

/hold for discussion if this approach is still valid

There are some follow up issues from the previous drop of 1.23 jobs that we should also follow up on:

https://github.com/kubernetes/test-infra/issues/29388
https://github.com/kubernetes/test-infra/issues/29390
https://github.com/kubernetes/sig-release/issues/2227

2023-08-30 08:22 UTC, xmudrii requested changes
We have some issue with periodic annotations that we should sort out before merging this PR. Let's sync about that and see how should we handle that.

2023-08-30 08:22 UTC, xmudrii commented on config/jobs/kubernetes/sig-release/release-branch-jobs/1.26.yaml
> +    fork-per-release-periodic-interval: ""
This is wrong, there must be one interval left here or we're going to run into issues the next time we rotate jobs.

2023-08-30 08:22 UTC, xmudrii commented on config/jobs/kubernetes/sig-release/release-branch-jobs/1.26.yaml
> +    fork-per-release-periodic-interval: ""
Same here.

2023-08-30 08:22 UTC, xmudrii commented on config/jobs/kubernetes/sig-release/release-branch-jobs/1.26.yaml
> +    fork-per-release-periodic-interval: ""
Same here.

2023-08-30 08:22 UTC, xmudrii commented on config/jobs/kubernetes/sig-release/release-branch-jobs/1.26.yaml
> +    fork-per-release-periodic-interval: ""
Same here.

2023-08-30 22:15 UTC, marosset approved these changes
windows changes LGTM

2023-08-30 22:17 UTC, jeremyrickard commented
/assign wojtek-t

2023-08-31 02:05 UTC, jeremyrickard commented
/assign michelle192837

2023-08-31 16:12 UTC, ameukam commented
/approve

2023-08-31 16:44 UTC, xmcqueen reviewed
/lgtm

2023-08-31 16:46 UTC, merged