migrate `promo-tools` jobs to community cluster
kubernetes/test-infra pull request #31063
Opened 2023-10-18 14:59 UTC by rjsadow

This PR moves promo-tools jobs to the community owned cluster.

ref: https://github.com/kubernetes/test-infra/issues/30277

/cc @cpanato @jeremyrickard @justaugustus @listx @puerco @saschagrunert
/cc @ameukam

2023-10-18 15:12 UTC, cpanato requested changes
i think we cannot move those because we use some secrets from gcp and then that makes sense to keep the jobs as is.

/hold

2023-10-19 07:09 UTC, saschagrunert reviewed
Would it be possible to move the secret to the `k8s-infra-prow-build` cluster? 

Which secret are we referring to?

2023-10-19 08:13 UTC, cpanato commented
> Would it be possible to move the secret to the `k8s-infra-prow-build` cluster?
> 
> Which secret are we referring to?

https://github.com/kubernetes/test-infra/pull/31063/files#diff-02a94ff8e4f303b60c3e34c4f93f0f2bf3f3de91e733461ded97f774b9ecb281L35-L39

do you think worth doing this change?

2024-02-27 09:10 UTC, ameukam commented
Let's not do this for the moment.
/close

2024-02-27 09:11 UTC, closed without merging