etcd: remove --failfast for robustness test.
kubernetes/test-infra pull request #32481
Opened 2024-04-19 21:29 UTC by siyuanfoundation

Each run in robustness test is different. Collecting more run data would be beneficial rather than only collecting data of a few runs if it gets unlucky.

2024-04-19 21:44 UTC, wenjiaswe commented
lgtm. Thanks!

2024-04-24 11:40 UTC, serathius requested changes
In the PR there are two changes, one is to remove --failfast, second to zip the results and put them in ${ARTIFACTS} directory. Second one makes sense to provide parity with github actions, however I don't understand the first one.

To remove the --failfast you need to not override results. That's not yet done, please split the PR or let's wait for https://github.com/etcd-io/etcd/pull/17827 to get merged.

2024-04-24 21:04 UTC, siyuanfoundation commented
merged https://github.com/etcd-io/etcd/pull/17827

2024-04-25 07:07 UTC, serathius commented
Could you send PR to remove --failfast from github actions too?

2024-04-25 07:29 UTC, merged