Update golang image to 1.22 for ibm-powervs-block-csi-driver jobs.
kubernetes/test-infra pull request #32661
Opened 2024-05-26 05:07 UTC by kishen-v

Update golang image to 1.22 for ibm-powervs-block-csi-driver jobs.

2024-05-26 13:02 UTC, mkumatag commented
/ok-to-test

2024-05-26 13:04 UTC, mkumatag requested changes
Any specific reason for bumping the golang version to 1.22 here?

2024-05-26 16:36 UTC, kishen-v commented
Hi @mkumatag,
The ibm-powervs-block-csi-driver will be using Go 1.22, hence updating the dependent workflows to use the same version. 

Reference issue from the ibm-powervs-block-csi-driver repo.:  https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/issues/671
Related PR in the ibm-powervs-block-csi-driver repo to bump go version to 1.22 : https://github.com/kubernetes-sigs/ibm-powervs-block-csi-driver/pull/673

Thanks!

2024-07-03 06:42 UTC, yussufsh approved these changes
/lgtm

2024-07-03 06:44 UTC, yussufsh commented
/retitle Update golang image to 1.22 for ibm-powervs-block-csi-driver jobs

2024-07-03 07:01 UTC, merged