add image publishing job for vsphere csi
kubernetes/test-infra pull request #33372
Opened 2024-08-26 23:03 UTC by divyenpatel

Add image pushing job for vsphere csi

2024-08-26 23:09 UTC, divyenpatel commented
/hold

wait for https://github.com/kubernetes/k8s.io/pull/7210 to merge

2024-08-28 20:18 UTC, divyenpatel commented
/hold cancel

2024-08-28 20:19 UTC, divyenpatel commented
cc: @upodroid

2024-08-28 20:20 UTC, divyenpatel commented on config/jobs/image-pushing/k8s-staging-csi-vsphere.yaml
> +              - --project=k8s-infra-staging-csi-vsphere
@upodroid is this section looks correct?

2024-08-28 20:45 UTC, upodroid requested changes

2024-08-28 20:45 UTC, upodroid commented on config/jobs/image-pushing/k8s-staging-csi-vsphere.yaml
> +              - --project=k8s-infra-staging-csi-vsphere
```suggestion
              - --project=k8s-staging-images
```

2024-08-28 20:45 UTC, upodroid commented on config/jobs/image-pushing/k8s-staging-csi-vsphere.yaml
> +              - --scratch-bucket=gs://k8s-infra-staging-csi-vsphere-gcb
```suggestion
              - --scratch-bucket=gs://k8s-staging-images-gcb
```

2024-08-28 21:28 UTC, xing-yang commented
/lgtm

2024-08-28 21:36 UTC, divyenpatel commented on config/jobs/image-pushing/k8s-staging-csi-vsphere.yaml
> +              - --project=k8s-infra-staging-csi-vsphere
accepted this change in the commit.

2024-08-28 23:43 UTC, upodroid approved these changes
LGTM

2024-08-28 23:44 UTC, merged